### Les01

### Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [105]:
import numpy as np

ar = np.array([[1,6],
               [2,8],
               [3,11],
               [3,10],
               [1,7]])

In [114]:
l_col = np.mean(ar[0:5, 0]) # Среднее значение по левому столбцу
r_col = np.mean(ar[0:5, 1]) # Среднее значение по правому столбцу

In [113]:
mean_a = ([l_col, r_col])

mean_a # Результат

[2.0, 8.4]

### Задание 2

Вычислите массив a_centered, отняв от значений массива 'ar' 
средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [52]:
a_centered = ar - mean_a

a_centered # Результат

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [115]:
sp = a_centered[:5, 0] * a_centered[:5, 1] # скалярное произведение срезов массива "a_centered", представленных ввиде векторов

sp

array([ 2.4, -0. ,  2.6,  1.6,  1.4])

In [116]:
sp = np.sum(sp) # Сумма элементов массива "sp"

sp

8.0

In [117]:
N = (np.shape(a_centered))[0] # Вычисление "N" путем извлечения по индексу показателя размерности (кол-ва строк)

N

5

In [118]:
a_centered_sp = sp / (N - 1) # Ковариация двух признаков. Зачем "N - 1"? Пока не ясно...

a_centered_sp # Результат

2.0

### * Задание 4

Число, которое мы получили в конце задания 3 является 
ковариацией двух признаков, содержащихся в массиве а.
В задании 3 мы делили сумму произведений центрированных 
признаков на N-1, а не на N, поэтому полученная нами величина 
является несмещенной оценкой ковариации.

В этом задании проверьте получившееся число, вычислив
ковариацию еще одним способом - с помощью функции np.cov.
В качестве аргумента m функция np.cov должна принимать транспонированный массив 'ar'.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 
ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [125]:
ar = np.transpose(ar) # Транспонирование матрицы "ar"

ar

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [128]:
cov_alt_result = (np.cov(ar))[0, 1] # Извлечение результата по индексу из ковариационной матрицы

cov_alt_result # Результат

2.0